# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 2812d218e1fdfb9c5d88f0b020c915a1074c11a2ac1e48d4d834418c8f48b46d92ce71f92f0bc22be7136a40d915143303d573da1e3a8c2802907a2d962e58a8

test:
  secret_key_base: 834d0bea10ea5a73a7349d257ef23997bc2f6a2a91e7f08c0d12be5930cbaf793c141c85cfcef6766609b146ba6fe91afe60da57541a16cdb0261e82548f8228

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
